<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Support\Facades\Auth;
use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;

class Product extends Model
{
    /** @use HasFactory<\Database\Factories\ProductFactory> */
    use HasFactory, HasSlug;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'slug',
        'description',
        'published_at',
        'price',
        'category_id',
        'store_id',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected function casts(): array
    {
        return [
            'price' => 'float',
            'quantity' => 'int',
            'published_at' => 'date',
            /**
             * Generated by the `wishlistedByCurrentUser` relationship.
             */
            'wishlisted_by_authenticated_user' => 'boolean',
        ];
    }

    public function getSlugOptions(): SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom('name')
            ->saveSlugsTo('slug');
    }

    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class);
    }

    public function thumbnail(): MorphMany
    {
        return $this->media()->where('collection_name', 'thumbnail');
    }

    public function images(): MorphMany
    {
        return $this->media()->where('collection_name', 'images');
    }

    public function CouponeCodes(): BelongsToMany
    {
        return $this->belongsToMany(CouponCode::class);
    }

    public function wishlistedByCurrentUser(): BelongsToMany
    {
        return $this->belongsToMany(User::class)->wherePivot('user_id', '=', Auth::id());
    }
}
